print("HEMALI"[3])
lent = len(input("What is your name?"))
lenth = str(lent)
print(type(lenth))
print(lent)
print("Your name has " + lenth + " characters")
print(2 ** 2)
print(float("100.34") + 1000)
print(str(299) + str(3344))
print(5//2)
print(f"Your score is {lent}")